### PR TITLE
WIP: various fixes to get it compile on Debian12 with osmocom:latest

### PR DESCRIPTION
**Pull request by laf0rge**
I have not tested this whatsoever, but I wanted to raise the PR to document the status.

I'm not sure if I find the time, but I'd love to explore and improve this code further.  Would you consider migrating it beneath https://gitea.osmocom.org/retronetworking/ or do you prefer github?

### CODE REVIEW

**Comment by Manawyrm** [comment]
> Would you consider migrating it beneath https://gitea.osmocom.org/retronetworking/ or do you prefer github?

Sure, I can just migrate it over. Do we want to keep just "ras" as the repo name over there, or should we think of something else?

**Comment by Manawyrm** [comment]
Otherwise, the changes all look very good, I'd want to merge them like this.

**Comment by laf0rge** [comment]
> > Would you consider migrating it beneath https://gitea.osmocom.org/retronetworking/ or do you prefer github?
> 
> Sure, I can just migrate it over. Do we want to keep just "ras" as the repo name over there, or should we think of something else?

I think we should call it yate-ras as its interface is specific to yate?  You should have sufficient gitea permissions to do the migration.

> Otherwise, the changes all look very good, I'd want to merge them like this.

They might look good, but keep in mind none of this has received any actual real-world testing... so maybe hold back a bit until either of us did?

**Comment by Manawyrm** [comment]
> so maybe hold back a bit until either of us did?

Fair point.
Are you willing to push these changes once again after the migration or should I wait until this is merged?

**Comment by laf0rge** [comment]
> > so maybe hold back a bit until either of us did?
> 
> Are you willing to push these changes once again after the migration or should I wait until this is merged?

A gitea migration should import not just the git repo, but also any open pull requests. So at least in theory, no further action like re-opening the PR should be required.  But certainly I'll resubmit there if needed.

**Comment by Manawyrm** [comment]
Repo moved over to https://gitea.osmocom.org/retronetworking/yate-ras, but your PR did not make it over there...

**Pull request closed without merging**
